### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by arjung24** [bilashcse/hoichoi-downloader#1]
C:\Users\Administrator\hoichoi-downloader>node app https://www.hoichoi.tv/show/title/eken-babu-web-series
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'request-promise'
Require stack:
- C:\Users\Administrator\hoichoi-downloader\services\series_details.js
- C:\Users\Administrator\hoichoi-downloader\app.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:746:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:974:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:92:18)[39m
    at Object.<anonymous> (C:\Users\Administrator\hoichoi-downloader\services\series_details.js:1:12)
[90m    at Module._compile (internal/modules/cjs/loader.js:1085:14)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:950:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:790:14)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:974:19)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [
    [32m'C:\\Users\\Administrator\\hoichoi-downloader\\services\\series_details.js'[39m,
    [32m'C:\\Users\\Administrator\\hoichoi-downloader\\app.js'[39m
  ]
}

C:\Users\Administrator\hoichoi-downloader>

Note: i set x-api-key and authorization in configs.js

**Comment by bilashcse** [comment]
Hello, please install : npm i request-promise. I think, now it will work perfectly @arjung24 . Anyway, you can update the module, today I have added login, and also other features. I think it will help you more. If you will take latest code from main branch, please update configs file. Read readme file, its already updated

**Comment by arjung24** [comment]
Thanks brother. The problem is i can't login via email and password. My account is number login system as it is needed OTP to login. U made the project simple now with this login system. But it is not convenient for me. Thanks for updating the module.

**Comment by bilashcse** [comment]
For this problem, i will try to give u another way. Hopefully, i will give you older way to download. Allow me some time

**Comment by bilashcse** [comment]
@arjung24  please pull the latest code from main branch. Now update configs, here I have added authorization, which will be found after login. You will  get this data from hoichoi, if you are login user, please check network & use headers data here. If authorization info exists in configs, then username, password will not require here, it will bypass login. Please give some feedback here after successful. 

Thanks

**Comment by arjung24** [comment]
@bilashcse same error brother. 1) i set authorization, email and password= not working
2) I set authorization only= not working
3) I set email and password only=not working

every time same error like previous
note: i installed nodejs and npm

**Comment by bilashcse** [comment]
Whats the error ?  Is this the error ? 
`Cannot find module 'request-promise'`

If this then please run the command : `npm i request-promise`

**Comment by arjung24** [comment]
C:\Users\Administrator\hoichoi-downloader>node app https://www.hoichoi.tv/show/title/eken-babu-web-series
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'request-promise'
Require stack:
- C:\Users\Administrator\hoichoi-downloader\services\series_details.js
- C:\Users\Administrator\hoichoi-downloader\app.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:746:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:974:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:92:18)[39m
    at Object.<anonymous> (C:\Users\Administrator\hoichoi-downloader\services\series_details.js:1:12)
[90m    at Module._compile (internal/modules/cjs/loader.js:1085:14)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:950:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:790:14)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:974:19)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [
    [32m'C:\\Users\\Administrator\\hoichoi-downloader\\services\\series_details.js'[39m,
    [32m'C:\\Users\\Administrator\\hoichoi-downloader\\app.js'[39m
  ]
}

C:\Users\Administrator\hoichoi-downloader>npm i request-promise
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN hoichoi-downloader@1.0.0 No repository field.

+ request-promise@4.2.6
added 259 packages from 215 contributors and audited 259 packages in 9.293s

34 packages are looking for funding
  run `npm fund` for details

found 7 vulnerabilities (2 moderate, 5 high)
  run `npm audit fix` to fix them, or `npm audit` for details

C:\Users\Administrator\hoichoi-downloader>

**Comment by arjung24** [comment]
what to do next brother?

**Comment by bilashcse** [comment]
try with this : `npm i request-promise@4.2.6`

**Comment by arjung24** [comment]
C:\Users\Administrator\hoichoi-downloader>npm i request-promise@4.2.6
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN hoichoi-downloader@1.0.0 No repository field.

+ request-promise@4.2.6
updated 1 package and audited 259 packages in 2.206s

34 packages are looking for funding
  run `npm fund` for details

found 7 vulnerabilities (2 moderate, 5 high)
  run `npm audit fix` to fix them, or `npm audit` for details

C:\Users\Administrator\hoichoi-downloader>

**Comment by bilashcse** [comment]
Only add  authorization if you dont have password.
Heres authorization or (username, password) needed

**Comment by arjung24** [comment]
i have password now so i set email and pass

**Comment by bilashcse** [comment]
then just add username & password only

**Comment by arjung24** [comment]
should i erase authorization line in config.js

**Comment by bilashcse** [comment]
yes

**Comment by bilashcse** [comment]
i am trying to replace request-promise with axios asap

**Comment by arjung24** [comment]
should i try anything else or i stop??

**Comment by arjung24** [comment]
i got this after erasing auth line and setting email and pass

C:\Users\Administrator\hoichoi-downloader>npm i request-promise@4.2.6
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN hoichoi-downloader@1.0.0 No repository field.

+ request-promise@4.2.6
updated 1 package and audited 259 packages in 2.156s

34 packages are looking for funding
  run `npm fund` for details

found 7 vulnerabilities (2 moderate, 5 high)
  run `npm audit fix` to fix them, or `npm audit` for details

C:\Users\Administrator\hoichoi-downloader>

**Comment by bilashcse** [comment]
Give me some time, replacing request-promise. I will inform you after finish.

**Comment by arjung24** [comment]
ok brother. thanks

**Comment by bilashcse** [comment]
@arjung24 Pull the latest code. Try to run now. Please inform me after checking.

**Comment by bilashcse** [comment]
Now no need to install request-promise. Just run to download

**Comment by arjung24** [comment]
C:\Users\Administrator\hoichoi-downloader>node app https://www.hoichoi.tv/show/title/eken-babu-web-series
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'axios'
Require stack:
- C:\Users\Administrator\hoichoi-downloader\services\series_details.js
- C:\Users\Administrator\hoichoi-downloader\app.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:746:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:974:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:92:18)[39m
    at Object.<anonymous> (C:\Users\Administrator\hoichoi-downloader\services\series_details.js:1:15)
[90m    at Module._compile (internal/modules/cjs/loader.js:1085:14)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:950:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:790:14)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:974:19)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [
    [32m'C:\\Users\\Administrator\\hoichoi-downloader\\services\\series_details.js'[39m,
    [32m'C:\\Users\\Administrator\\hoichoi-downloader\\app.js'[39m
  ]
}

C:\Users\Administrator\hoichoi-downloader>

**Comment by bilashcse** [comment]
Run `npm i axios`

**Comment by arjung24** [comment]
C:\Users\Administrator\hoichoi-downloader>npm i axios
npm WARN hoichoi-downloader@1.0.0 No repository field.

+ axios@0.21.1
added 214 packages from 162 contributors and audited 214 packages in 8.918s

33 packages are looking for funding
  run `npm fund` for details

found 6 vulnerabilities (2 moderate, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details

C:\Users\Administrator\hoichoi-downloader>

**Comment by arjung24** [comment]
is it ok now??

**Comment by arjung24** [comment]
C:\Users\Administrator\hoichoi-downloader>npm i axios
npm WARN hoichoi-downloader@1.0.0 No repository field.

+ axios@0.21.1
added 214 packages from 162 contributors and audited 214 packages in 8.918s

33 packages are looking for funding
  run `npm fund` for details

found 6 vulnerabilities (2 moderate, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details

C:\Users\Administrator\hoichoi-downloader>node app https://www.hoichoi.tv/show/title/eken-babu-web-series
Something went wrong. Request failed with status code 404

C:\Users\Administrator\hoichoi-downloader>

**Comment by bilashcse** [comment]
can u give me your gmail address please ?

**Comment by bilashcse** [comment]
Here, i think auth issue. Can u recheck configs file ? 

if authorization exists then remove others, if  username, password exists then remove authorization

**Comment by arjung24** [comment]
> can u give me your gmail address please ?

gjoyanta970@gmail.com

**Comment by arjung24** [comment]
> Here, i think auth issue. Can u recheck configs file ?
> 
> if authorization exists then remove others, if username, password exists then remove authorization

I removed auth and keep only email and password

**Comment by arjung24** [comment]
C:\Users\Administrator\hoichoi-downloader>node app https://www.hoichoi.tv/show/title/eken-babu-web-series
Something went wrong. Request failed with status code 404

C:\Users\Administrator\hoichoi-downloader>

**Comment by arjung24** [comment]
C:\Users\Administrator\hoichoi-downloader>node app https://www.hoichoi.tv/shows/watch-murder-in-the-hills-bengali-web-series-online
Current Series / Movie Name: Watch Murder in the Hills Full Bengali Web Series Online
Sorry, Error occurred to get token
Something went wrong. Request failed with status code 401

C:\Users\Administrator\hoichoi-downloader>

**Comment by arjung24** [comment]
C:\Users\Administrator\hoichoi-downloader>node app https://www.hoichoi.tv/movies/watch-hiralal-bengali-movie-online
Current Series / Movie Name: Watch Hiralal Full Bengali Movie Online
Sorry, Error occurred to get token
Something went wrong. Request failed with status code 401

C:\Users\Administrator\hoichoi-downloader>

**Comment by arjung24** [comment]
finally succeeded

C:\Users\Administrator\hoichoi-downloader>node app https://www.hoichoi.tv/shows/watch-rahasya-romancha-series-bengali-web-series-online
Current Series / Movie Name: Watch Rahasya Romancha Series Full Bengali Web Series Online
Season 1 : Jhontu Motors Part 1
 ████████████████████████████████████████ 100% | ETA: 0s | 100/100
Season 1 : Jhontu Motors Part 2
 ████████████████████████████████████████ 100% | ETA: 0s | 100/100
Season 1 : Shokuni Part 1
 ████████████████████████████████████████ 100% | ETA: 0s | 100/100
Season 1 : Shokuni Part 2
 ████████████████████████████████████████ 100% | ETA: 0s | 100/100
Season 1 : Jhorer Raat
 ████████████████████████████████████████ 100% | ETA: 0s | 100/100
Season 2 : Jhontu Motors: Origin - Part 1
 ████████████████████████████████████████ 100% | ETA: 0s | 100/100
Season 2 : Jhontu Motors: Origin - Part 2
 ████████████████████████████████████████ 100% | ETA: 0s | 100/100
Season 2 : Jhontu Motors: Origin - Part 3
 ████████████████████████████████████████ 100% | ETA: 0s | 100/100
Season 2 : The Crime Writer
 ████████████████████████████████████████ 100% | ETA: 0s | 100/100
Season 2 : The Gym Instructor
 ████████████████████████████████████████ 100% | ETA: 0s | 100/100
Season 2 : Kalo Nekre
 ████████████████████████████████████████ 100% | ETA: 0s | 100/100
Season 3 : Homecoming
 ████████████████████████████████████████ 100% | ETA: 0s | 100/100
Season 3 : Code Name Kalo Nekre
 ██████████████████████░░░░░░░░░░░░░░░░░░ 56% | ETA: 3s | 56/100

**Comment by arjung24** [comment]
default downloading 720P quality. is it possible to download in 1080P quality??

**Comment by arjung24** [comment]
Again same problem

C:\Users\Administrator\hoichoi-downloader>node app https://www.hoichoi.tv/shows/watch-ha-ja-ba-ra-la-bengali-web-series-online
Current Series / Movie Name: Watch Ha Ja Ba Ra La Full Bengali Web Series Online
Something went wrong. Request failed with status code 401

C:\Users\Administrator\hoichoi-downloader>
